name = "gleamoire"
version = "2.0.0"
gleam = ">= 1.11.0"

description = "A handy grimoire for gleam! Get documentation for your fave packages directly in the terminal."
licences = ["Apache-2.0"]
repository = { type = "github", user = "GearsDatapacks", repo = "gleamoire" }

internal_modules = ["gleamoire/*"]

[dependencies]
glitzer = ">= 1.1.1 and < 3.0.0"
gleam_stdlib = ">= 0.44.0 and < 1.0.0"
gleam_package_interface = ">= 1.1.0 and < 4.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
gleescript = ">= 1.4.0 and < 2.0.0"
gleamyshell = ">= 2.0.1 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_httpc = ">= 2.2.0 and < 6.0.0"
tom = ">= 1.0.1 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 5.0.0"
commonmark = ">= 0.1.8 and < 1.0.0"
gleam_community_ansi = ">= 1.4.1 and < 2.0.0"
gleam_json = ">= 2.1.0 and < 4.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.0 and < 2.0.0"
